//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use crate::role_permissions;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
    pub status: i32,
    pub r#type: i32,
    pub icon: Option<String>,
    pub sort: i32,
    pub parent_id: Option<String>,
    pub path: Option<String>,
    pub create_time: Option<DateTime>,
    pub update_time:  Option<DateTime>,
    pub sofl_delete: i32,
    pub create_user_id: Option<i32>,
    pub update_user_id: Option<i32>,
    pub is_admin_visible: i32,
    pub is_user_visible: i32,
    pub key_name: Option<String>,
    pub file_name: Option<String>,
}


#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    RolePermissions,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::RolePermissions => Entity::has_many(super::role_permissions::Entity)
                .from(Column::Id)
                .to(super::role_permissions::Column::PermissionId)
                .into(),
        }
    }
}

impl Related<role_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolePermissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
