//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::user::Entity as User;
pub use super::user_roles::Entity as UserRoles;
