//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use crate::user_roles;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_name: String,
    pub name: Option<String>,
    pub password: Option<String>,
    pub nick_name: Option<String>,
    pub avatar: Option<String>,
    pub email: Option<String>,
    pub sex:  Option<i32>,
    pub phone_number: Option<String>,
    pub last_login_ip: Option<String>,
    pub last_login_time: Option<String>,
    pub status: i32,
    pub create_time: Option<DateTime>,
    pub update_time:  Option<DateTime>,
    pub sofl_delete: i32,
    pub create_user_id: Option<i32>,
    pub update_user_id: Option<i32>,
    pub code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    UserRoles,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::UserRoles => Entity::has_many(super::user_roles::Entity)
                .from(Column::Id)
                .to(super::user_roles::Column::UserId)
                .into(),
        }
    }
}

impl Related<user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}